/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BankPage = {
  id: number;
  bank_page_id: number;
  reference?: number;
  debit_or_credit?: "חובה" | "זכות";
  cumulative_balance?: number;
  cumulative_balance_calculated?: number;
  match_number?: number;
  account_id?: string;
  sum?: number;
  details?: string;
  account_name?: string;
  date?: string;
  adjusted_record?: string;
}[];
