/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BankPage = {
  accountId?: string;
  accountName?: string;
  adjustedRecord?: string;
  bankPageId: number;
  cumulativeBalance?: number;
  cumulativeBalanceCalculated?: number;
  date?: string;
  debitOrCredit?: "חובה" | "זכות";
  details?: string;
  id: number;
  matchNumber?: number | null;
  reference?: number;
  sum?: number;
}[];
