/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Record = {
  account_id: string;
  batch_id: number;
  counter_account_id?: string;
  counter_account_name?: string;
  cumulative_balance?: number;
  cumulative_balance_by_sector?: number;
  cumulative_balance_by_sort_key?: number;
  cumulative_balance_without_opening_balance?: number;
  cumulative_balance_of_open_sum_in_record?: number;
  debit_or_credit?: "חובה" | "זכות";
  debit_or_credit_number?: -1 | 1;
  estimated_sum?: number;
  foreign_currency_credit?: number | null;
  foreign_currency_cumulative_balance?: number;
  foreign_currency_cumulative_balance_without_opening_balance?: number;
  foreign_currency_debit?: number | null;
  foreign_currency_sum?: number;
  foreign_currency_sum_closed_in_record?: number;
  foreign_currency_sun_open_in_record?: number;
  id: number;
  match_number_card_analysis?: number | null;
  shekel_credit?: number | null;
  shekel_debit?: number | null;
  shekel_sum?: number;
  shekel_sum_closed_in_record?: number;
  shekel_sum_open_in_record?: number;
  transaction_id: number;
}[];
